-- src/config/juice_schema.lua
-- The single registry of every tunable in the game. juice.json is the file you edit; this
-- schema is what makes that file safe and what the juice editor draws its controls from:
--   * every key has a type, a default, and (for numbers) a min/max the loader clamps to
--   * missing keys fall back to defaults, unknown keys are kept but warned about
--
-- If you find yourself typing a game-feel number into code, add an entry here instead.
--
-- Entry fields:
--   key      dotted path in juice.json ("timing.early_ms")
--   type     number | int | bool | enum | color
--   default, min, max, step, values (enum), desc
--   unit     slider range hint for the editor: x / y (virtual width / height), px
--   restart  true when a change only shows after restarting the game
--   log      the editor's slider is logarithmic (frequencies)

local FONTS = {
  { id = "builtin",   name = "LÖVE default" },
  { id = "bungee",    file = "Bungee.ttf",        name = "Bungee (display)" },
  { id = "russo",     file = "RussoOne.ttf",      name = "Russo One (heavy)" },
  { id = "orbitron",  file = "Orbitron.ttf",      name = "Orbitron (techno)" },
  { id = "sharetech", file = "ShareTechMono.ttf", name = "Share Tech Mono (mono)" },
  { id = "teko",      file = "Teko.ttf",          name = "Teko (tall)" },
}
local FONT_IDS = {}
for _, f in ipairs(FONTS) do FONT_IDS[#FONT_IDS + 1] = f.id end

local schema = {
  version = 1,
  fonts = FONTS,

  groups = {
    { id = "layout",      title = "Layout",      desc = "Where the board and the text sit, and the screen's colors." },
    { id = "type",        title = "Type",        desc = "Fonts and text sizes." },
    { id = "pads",        title = "Pads",        desc = "The grey rubber buttons: shape, shading, how they press." },
    { id = "lights",      title = "Lights",      desc = "The RGB LEDs under the pads: glow, timing, feedback colors. Each pad's own color is set per level in the level editor." },
    { id = "timing",      title = "Timing",      desc = "Latency compensation, and how the player's turn reads presses (it judges the sequence, not the timing)." },
    { id = "flow",        title = "Round Flow",  desc = "What a round is made of: count-in, demo, the player's turn (how long they get), and how the pattern grows." },
    { id = "rules",       title = "Rules",       desc = "Mistakes, lives, retries." },
    { id = "scoring",     title = "Scoring",     desc = "Points and the combo multiplier." },
    { id = "wrong_sound", title = "Wrong Sound", desc = "What a wrong press sounds like: the pad's own sample, pitched, low-passed and dirtied." },
    { id = "feel",        title = "Feel",        desc = "Shake, punch and pop: the motion that sells a hit or a miss." },
    { id = "audio",       title = "Audio",       desc = "Volumes, metronome, velocity." },
    { id = "song",        title = "Song",        desc = "A song is levels built up one on top of another. Clearing one locks its loop in under the next: the pads strobe gold and a VO line plays. After the last, the full track plays with the pads going off in time." },
    { id = "display",     title = "Display",     desc = "Window and virtual resolution." },
    { id = "hot_reload",  title = "Hot Reload",  desc = "Live re-read of juice.json while the game runs." },
    { id = "debug",       title = "Debug",       desc = "Developer overlays." },
  },

  entries = {
    { key = "schema_version", type = "int", default = 1, min = 1, max = 999,
      desc = "Schema version this file was written for." },

    -- ------------------------------------------------------------------ layout
    { key = "layout.background", type = "color", default = { 0.055, 0.058, 0.066 },
      desc = "Screen background." },
    { key = "layout.board_x", type = "int", default = 640, min = 0, max = 4096, unit = "x",
      desc = "Center of the pad board, across." },
    { key = "layout.board_y", type = "int", default = 484, min = 0, max = 4096, unit = "y",
      desc = "Center of the pad board, down." },
    { key = "layout.board_size", type = "int", default = 452, min = 80, max = 4096, unit = "y",
      desc = "Width (and height) of the 2x2 grid of pads." },
    { key = "layout.pad_gap", type = "int", default = 22, min = 0, max = 400, unit = "px",
      desc = "Gap between neighbouring pads." },
    { key = "layout.frame", type = "bool", default = true,
      desc = "Draw the device body the pads sit in." },
    { key = "layout.frame_color", type = "color", default = { 0.105, 0.108, 0.118 },
      desc = "Color of the device body." },
    { key = "layout.frame_padding", type = "int", default = 30, min = 0, max = 400, unit = "px",
      desc = "How far the device body extends past the pads." },
    { key = "layout.frame_corner", type = "int", default = 30, min = 0, max = 400, unit = "px",
      desc = "Corner radius of the device body." },
    { key = "layout.title_y", type = "int", default = 36, min = 0, max = 4096, unit = "y",
      desc = "Level name and round counter, top center." },
    { key = "layout.status_y", type = "int", default = 84, min = 0, max = 4096, unit = "y",
      desc = "The big status word: WATCH, YOUR TURN, NICE." },
    { key = "layout.hud_margin", type = "int", default = 40, min = 0, max = 2000, unit = "px",
      desc = "Distance of the score (left) and lives (right) from the screen edges." },
    { key = "layout.hint_y", type = "int", default = 752, min = 0, max = 4096, unit = "y",
      desc = "The key hint line under the board." },
    { key = "layout.show_hint", type = "bool", default = true,
      desc = "Show the 'Q W A S or click the pads' hint." },
    { key = "layout.show_key_labels", type = "bool", default = true,
      desc = "Engrave each pad with its key (Q W A S)." },
    { key = "layout.key_label_color", type = "color", default = { 0.25, 0.255, 0.27 },
      desc = "Color of the engraved key letters." },
    { key = "layout.text_color", type = "color", default = { 0.92, 0.93, 0.95 },
      desc = "Main text color." },
    { key = "layout.dim_color", type = "color", default = { 0.45, 0.47, 0.52 },
      desc = "Secondary text: hints, labels." },
    { key = "layout.accent_color", type = "color", default = { 1.0, 0.78, 0.25 },
      desc = "Accent: score, combo, YOUR TURN." },
    { key = "layout.good_color", type = "color", default = { 0.45, 1.0, 0.6 },
      desc = "Text color for a cleared round." },
    { key = "layout.bad_color", type = "color", default = { 1.0, 0.36, 0.3 },
      desc = "Text color for a failed round and lost lives." },

    -- ------------------------------------------------------------------ type
    { key = "type.font", type = "enum", default = "bungee", values = FONT_IDS,
      desc = "Font for the status word, titles and the score." },
    { key = "type.label_font", type = "enum", default = "sharetech", values = FONT_IDS,
      desc = "Font for hints, key labels and small text." },
    { key = "type.status_size", type = "int", default = 58, min = 8, max = 400,
      desc = "Size of the status word." },
    { key = "type.title_size", type = "int", default = 28, min = 8, max = 200,
      desc = "Size of the level name line." },
    { key = "type.hud_size", type = "int", default = 30, min = 8, max = 200,
      desc = "Size of the score and lives." },
    { key = "type.hint_size", type = "int", default = 20, min = 8, max = 120,
      desc = "Size of the hint line." },
    { key = "type.label_size", type = "int", default = 26, min = 8, max = 200,
      desc = "Size of the key letters on the pads." },

    -- ------------------------------------------------------------------ pads
    { key = "pads.color", type = "color", default = { 0.37, 0.38, 0.40 },
      desc = "The grey of the rubber pads." },
    { key = "pads.rim_color", type = "color", default = { 0.20, 0.205, 0.215 },
      desc = "Dark rim around each pad." },
    { key = "pads.rim_width", type = "number", default = 4, min = 0, max = 40, step = 0.5,
      desc = "Width of the rim." },
    { key = "pads.corner", type = "number", default = 16, min = 0, max = 200, step = 1,
      desc = "Corner radius of a pad." },
    { key = "pads.highlight", type = "number", default = 0.10, min = 0, max = 0.6, step = 0.01,
      desc = "Soft top highlight on the rubber." },
    { key = "pads.translucency", type = "number", default = 0.55, min = 0, max = 1, step = 0.01,
      desc = "How much the light underneath tints the pad face. 0 = solid grey with only a halo; 1 = the face glows the light's color." },
    { key = "pads.press_scale", type = "number", default = 0.94, min = 0.7, max = 1, step = 0.005,
      desc = "Size of a pad while held down." },
    { key = "pads.press_darken", type = "number", default = 0.22, min = 0, max = 1, step = 0.01,
      desc = "How much darker a held pad gets." },
    { key = "pads.press_in_s", type = "number", default = 0.025, min = 0, max = 0.5, step = 0.005,
      desc = "Time for a pad to go down." },
    { key = "pads.press_out_s", type = "number", default = 0.12, min = 0, max = 1, step = 0.01,
      desc = "Time for a pad to spring back up." },

    -- ------------------------------------------------------------------ lights
    { key = "lights.idle_level", type = "number", default = 0.06, min = 0, max = 1, step = 0.01,
      desc = "How lit a pad is at rest, in its own color." },
    { key = "lights.brightness", type = "number", default = 1.0, min = 0, max = 2, step = 0.01,
      desc = "Overall LED brightness." },
    { key = "lights.glow_size", type = "number", default = 64, min = 0, max = 400, step = 1,
      desc = "How far the colored halo reaches past a lit pad, in pixels." },
    { key = "lights.glow_strength", type = "number", default = 0.9, min = 0, max = 3, step = 0.01,
      desc = "Brightness of the halo." },
    { key = "lights.edge_bleed", type = "number", default = 0.7, min = 0, max = 3, step = 0.01,
      desc = "The thin bright line of light escaping around a lit pad's edge." },
    { key = "lights.attack_s", type = "number", default = 0.01, min = 0, max = 0.5, step = 0.005,
      desc = "Fade-in time of a light." },
    { key = "lights.hold_s", type = "number", default = 0.10, min = 0, max = 2, step = 0.01,
      desc = "How long a button's light stays fully on: every button is a tap of the same length (then it fades over decay_s)." },
    { key = "lights.decay_s", type = "number", default = 0.30, min = 0, max = 3, step = 0.01,
      desc = "Fade-out time after the hold." },
    { key = "lights.velocity_brightness", type = "number", default = 0.4, min = 0, max = 1, step = 0.01,
      desc = "How much a button of soft notes dims its light (its loudest note counts). 0 = every button full brightness." },
    { key = "lights.demo_level", type = "number", default = 1.0, min = 0, max = 2, step = 0.01,
      desc = "Brightness of the demo lights." },
    { key = "lights.press_level", type = "number", default = 0, min = 0, max = 2, step = 0.01,
      desc = "Extra light while a pad is held down. 0 = none: a press lights the pad exactly as the demo lights that button." },
    { key = "lights.correct_white", type = "number", default = 0, min = 0, max = 1, step = 0.01,
      desc = "White mixed into the light of a correct press, on top of the demo's light. 0 = a correct press looks exactly like the demo." },
    { key = "lights.turn_color", type = "color", default = { 0.2, 1.0, 0.35 },
      desc = "Color all four pads flash on the beat after the demo to say it's the player's turn, and pulse on every beat after." },
    { key = "lights.turn_level", type = "number", default = 1.0, min = 0, max = 2, step = 0.01,
      desc = "Brightness of that first flash, on the turn's first beat." },
    { key = "lights.turn_pulse_level", type = "number", default = 0.1, min = 0, max = 2, step = 0.01,
      desc = "Brightness of the pulse on every beat after it, until the turn is over." },
    { key = "lights.wrong_color", type = "color", default = { 1.0, 0.12, 0.08 },
      desc = "Flash color of a wrong press, and of all four pads when a guess is wrong." },
    { key = "lights.wrong_s", type = "number", default = 0.4, min = 0, max = 3, step = 0.01,
      desc = "How long the wrong flash lasts." },
    { key = "lights.fail_s", type = "number", default = 0.8, min = 0, max = 3, step = 0.01,
      desc = "How long all four pads flash red when a guess is wrong (too many wrong presses, or stalling too long)." },
    { key = "lights.miss_color", type = "color", default = { 0.6, 0.08, 0.06 },
      desc = "Color shown on the pad that was due when the player stalled too long (the wait or the grace ran out)." },
    { key = "lights.miss_s", type = "number", default = 0.5, min = 0, max = 3, step = 0.01,
      desc = "How long the missed-button light lasts." },
    { key = "lights.breathe", type = "bool", default = true,
      desc = "Pads slowly breathe their colors on the title screen." },
    { key = "lights.breathe_speed", type = "number", default = 0.5, min = 0.05, max = 4, step = 0.05,
      desc = "Breaths per second on the title screen." },

    -- ------------------------------------------------------------------ timing
    { key = "timing.audio_offset_ms", type = "number", default = 0, min = -100, max = 500, step = 1,
      desc = "How late you hear the audio (Bluetooth headphones: 150-250). Lights and judging shift by this so they match what you hear." },
    { key = "timing.early_ms", type = "number", default = 150, min = 0, max = 500, step = 1,
      desc = "A press this soon before the turn's first beat (the green flash) already counts as the turn's first press." },
    { key = "timing.together_ms", type = "number", default = 50, min = 0, max = 500, step = 1,
      desc = "Buttons starting this close together light together in the demo, so in the turn they can be pressed in either order." },

    -- ------------------------------------------------------------------ flow
    { key = "flow.title_s", type = "number", default = 1.6, min = 0, max = 10, step = 0.1,
      desc = "How long the level name shows before the first round." },
    { key = "flow.count_in_beats", type = "int", default = 4, min = 0, max = 16,
      desc = "Beats of count-in before a level's first demo." },
    { key = "flow.demo_repeats", type = "int", default = 1, min = 1, max = 8,
      desc = "How many times the board plays the pattern before the player's turn. The turn starts on the beat the demo ends: the pads flash green." },
    { key = "flow.wait_beats", type = "int", default = 16, min = 0, max = 64,
      desc = "Beats the player has to start the sequence after the green flash; then the guess counts as wrong. 0 = as long as they like." },
    { key = "flow.grace_beats", type = "number", default = 4, min = 0.5, max = 32, step = 0.5,
      desc = "Once the player has started, how long they can stall before the guess counts as wrong: beats past when the next button would be due if they were playing in time." },
    { key = "flow.rest_beats", type = "number", default = 1, min = 0, max = 16, step = 0.5,
      desc = "Beats at least between the end of the player's turn and the next demo, which then waits for the next bar (in a song, the loop grid)." },
    { key = "flow.result_beats", type = "number", default = 2, min = 0, max = 16, step = 0.5,
      desc = "Beats the round's result (PERFECT!, NICE!, KEEP GOING) stays up after your turn." },
    { key = "flow.grow", type = "enum", default = "buttons", values = { "buttons", "bars" },
      desc = "How the pattern grows round to round. buttons = like Simon: one more step each round until the whole loop is built (a step is a round box drawn in the level editor, or a button in none). bars = whole bars at a time." },
    { key = "flow.start_buttons", type = "int", default = 1, min = 1, max = 64,
      desc = "(grow = buttons) Steps in the first round (a step: a round box's buttons, or one button)." },
    { key = "flow.buttons_per_round", type = "int", default = 1, min = 1, max = 16,
      desc = "(grow = buttons) Steps added each round." },
    { key = "flow.start_bars", type = "int", default = 1, min = 1, max = 64,
      desc = "(grow = bars) Bars of the level's pattern in the first round." },
    { key = "flow.bars_per_round", type = "int", default = 1, min = 0, max = 64,
      desc = "(grow = bars) Bars added each round until the whole pattern is played. 0 = the first round is the whole level." },
    { key = "flow.demo_sound", type = "bool", default = true,
      desc = "The demo plays the MIDI with the lights. Off = lights only (harder)." },

    -- ------------------------------------------------------------------ rules
    { key = "rules.mistakes_allowed", type = "int", default = 1, min = 0, max = 32,
      desc = "Wrong presses forgiven in a turn: the player carries on from where they were. One more and the guess is wrong. 0 = like Simon, the first wrong press ends it." },
    { key = "rules.lives", type = "int", default = 0, min = 0, max = 20,
      desc = "(on_fail = retry_round / restart_level) Failed rounds before game over. 0 = no lives and no game over: as many tries as it takes. Hidden with on_fail = continue, where nothing fails." },
    { key = "rules.extra_press_is_mistake", type = "bool", default = true,
      desc = "A press of a pad that isn't due next counts as a mistake. Off = it only sounds wrong: the player can try pads until they find the right one." },
    { key = "rules.on_fail", type = "enum", default = "retry_round", values = { "continue", "retry_round", "restart_level" },
      desc = "After a wrong guess (too many wrong presses, or stalling too long): retry_round = TRY AGAIN, the same round again (demo and all) until it's right; restart_level = back to the level's first round; continue = carry on to the next round anyway (it just scores less: no round bonus, no combo). Retrying costs a life unless lives = 0." },

    -- ------------------------------------------------------------------ scoring
    { key = "scoring.correct", type = "int", default = 100, min = 0, max = 10000,
      desc = "Points for each correct press in the sequence (before the multiplier)." },
    { key = "scoring.round_bonus", type = "int", default = 250, min = 0, max = 100000,
      desc = "Bonus for clearing a round." },
    { key = "scoring.level_bonus", type = "int", default = 1000, min = 0, max = 100000,
      desc = "Bonus for clearing a level." },
    { key = "scoring.combo_step", type = "int", default = 8, min = 1, max = 128,
      desc = "Correct hits in a row per step up of the multiplier." },
    { key = "scoring.combo_max", type = "int", default = 4, min = 1, max = 16,
      desc = "Highest multiplier." },

    -- ------------------------------------------------------------------ wrong sound
    { key = "wrong_sound.enabled", type = "bool", default = true,
      desc = "Wrong presses play the pad's sound mangled. Off = they play it clean." },
    { key = "wrong_sound.pitch_semitones", type = "number", default = -3, min = -24, max = 24, step = 0.1,
      desc = "Pitch shift of a wrong hit, in semitones (also changes its speed, like a tape)." },
    { key = "wrong_sound.lowpass_hz", type = "number", default = 650, min = 60, max = 20000, step = 10, log = true,
      desc = "Low-pass cutoff: lower = more muffled." },
    { key = "wrong_sound.resonance", type = "number", default = 5, min = 0.5, max = 20, step = 0.1,
      desc = "Low-pass resonance (Q). Higher rings at the cutoff and grates more." },
    { key = "wrong_sound.drive", type = "number", default = 3, min = 1, max = 30, step = 0.1,
      desc = "Distortion. 1 = clean." },
    { key = "wrong_sound.volume_db", type = "number", default = -4, min = -36, max = 12, step = 0.5,
      desc = "Level of a wrong hit relative to a clean one." },

    -- ------------------------------------------------------------------ feel
    { key = "feel.shake_px", type = "number", default = 10, min = 0, max = 100, step = 0.5,
      desc = "Board shake on a wrong hit or a miss." },
    { key = "feel.shake_s", type = "number", default = 0.25, min = 0, max = 2, step = 0.01,
      desc = "Length of the shake." },
    { key = "feel.hit_punch", type = "number", default = 0, min = 0, max = 0.4, step = 0.005,
      desc = "A correctly pressed pad pops up by this much (fraction of its size). 0 = no pop, like the demo." },
    { key = "feel.punch_s", type = "number", default = 0.14, min = 0, max = 1, step = 0.01,
      desc = "Length of the pop." },
    { key = "feel.status_pop", type = "number", default = 0.25, min = 0, max = 1.5, step = 0.01,
      desc = "The status word starts this much bigger and settles." },
    { key = "feel.status_pop_s", type = "number", default = 0.2, min = 0, max = 2, step = 0.01,
      desc = "How long the status word takes to settle." },

    -- ------------------------------------------------------------------ audio
    { key = "audio.master_volume", type = "number", default = 1.0, min = 0, max = 1.5, step = 0.01,
      desc = "Everything." },
    { key = "audio.sample_volume", type = "number", default = 1.0, min = 0, max = 2, step = 0.01,
      desc = "The MIDI's samples (demo and player)." },
    { key = "audio.backing_volume", type = "number", default = 0.75, min = 0, max = 1.5, step = 0.01,
      desc = "The level's backing track. 0 = no backing." },
    { key = "audio.click_volume", type = "number", default = 0.5, min = 0, max = 1.5, step = 0.01,
      desc = "Metronome clicks." },
    { key = "audio.metronome", type = "enum", default = "count_ins", values = { "off", "count_ins", "always" },
      desc = "When the metronome clicks: never, during the count-in (and the wait for the next demo), or on every beat." },
    { key = "audio.velocity_sensitivity", type = "number", default = 0.35, min = 0, max = 1, step = 0.01,
      desc = "How much a note's velocity sets its volume (Ableton Simpler's Vel > Vol)." },

    -- ------------------------------------------------------------------ song
    { key = "song.clear_beats", type = "int", default = 8, min = 1, max = 32,
      desc = "Beats the gold celebration lasts after a level is cleared, before the next level's count-in. The level's loop is locked in and plays under it." },
    { key = "song.clear_color", type = "color", default = { 1.0, 0.72, 0.12 },
      desc = "The celebration's gold." },
    { key = "song.clear_glow", type = "number", default = 0.5, min = 0, max = 2, step = 0.01,
      desc = "Steady gold glow under the flashes." },
    { key = "song.clear_level", type = "number", default = 1.7, min = 0, max = 2, step = 0.01,
      desc = "Brightness at the peak of each gold flash." },
    { key = "song.clear_flashes_per_beat", type = "int", default = 4, min = 1, max = 8,
      desc = "Gold flashes per beat (4 = 16th notes), in time with the music." },
    { key = "song.clear_white", type = "number", default = 0.35, min = 0, max = 1, step = 0.01,
      desc = "White mixed into the flash on every beat." },
    { key = "song.clear_punch", type = "number", default = 0.06, min = 0, max = 0.4, step = 0.005,
      desc = "Every pad pops by this much (fraction of its size) on each beat of the celebration." },
    { key = "song.tint", type = "number", default = 0.9, min = 0, max = 1, step = 0.01,
      desc = "How much the celebration's gold and the finale's colors show through the rubber (pads.translucency for everything else)." },
    { key = "song.locked_volume", type = "number", default = 0.6, min = 0, max = 1.5, step = 0.01,
      desc = "Volume of the loops already locked in while a later level is built, so they sit back and the new part is center stage. 1 = as loud as when you built them. (During a level's gold celebration its loop plays at full volume.)" },
    { key = "song.vo_volume", type = "number", default = 1.0, min = 0, max = 2, step = 0.01,
      desc = "The VO line played when a level is cleared (each level's line is set in the song)." },
    { key = "song.vo_beat", type = "number", default = 1, min = 0, max = 8, step = 0.25,
      desc = "Beats after the last turn ends that the VO line comes in." },
    { key = "song.finale_volume", type = "number", default = 1.0, min = 0, max = 1.5, step = 0.01,
      desc = "The full track played after the last level." },
    { key = "song.finale_level", type = "number", default = 1.5, min = 0, max = 2, step = 0.01,
      desc = "Pad brightness at the peak of each hit during the finale." },
    { key = "song.finale_react", type = "number", default = 0.6, min = 0, max = 1, step = 0.01,
      desc = "How much the track's loudness drives the finale lights. 0 = the same pattern all the way through." },
    { key = "song.finale_steps_per_beat", type = "int", default = 4, min = 1, max = 8,
      desc = "Light hits per beat in the finale (4 = 16th notes)." },
    { key = "song.finale_white", type = "number", default = 0.5, min = 0, max = 1, step = 0.01,
      desc = "White flash on all four pads at the top of every bar of the finale." },

    -- ------------------------------------------------------------------ display
    { key = "display.virtual_width", type = "int", default = 1280, min = 320, max = 4096, restart = true,
      desc = "Width the game is laid out at; it scales to the window." },
    { key = "display.virtual_height", type = "int", default = 800, min = 240, max = 4096, restart = true,
      desc = "Height the game is laid out at." },
    { key = "display.window_width", type = "int", default = 1280, min = 320, max = 7680, restart = true,
      desc = "Window width." },
    { key = "display.window_height", type = "int", default = 800, min = 240, max = 4320, restart = true,
      desc = "Window height." },
    { key = "display.fullscreen", type = "bool", default = false, restart = true,
      desc = "Start fullscreen. F11 toggles." },

    -- ------------------------------------------------------------------ hot reload / debug
    { key = "hot_reload.enabled", type = "bool", default = true,
      desc = "Re-read juice.json when it changes on disk while the game runs." },
    { key = "hot_reload.poll_interval_s", type = "number", default = 0.4, min = 0.05, max = 10, step = 0.05,
      desc = "How often to check the file." },
    { key = "debug.autoplay", type = "bool", default = false,
      desc = "The game plays the player's turn itself: the sequence, in time." },
  },
}

return schema
